### ISSUE TITLE
Don't prompt user to open Keppel when USB device plugged in

### ISSUE THREAD

**Issue by tobiasmcnulty** [LSHTM-ORK/ODK_Biometrics#17]
When a USB fingerprint reader is plugged in, as of the latest code, we now receive a message prompting us "Would you like to open Keppel every time <device> is plugged in?"

Since Keppel is used only from ODK, it does not make sense to open Keppel when the USB device is plugged in. While it does not break anything per se, the message is extraneous and confusing for the user, since it looks a lot like the permission prompt.

**Comment by seadowg** [comment]
@tobiasmcnulty this pop up allows you to set Keppel as the default app for the USB device (by checking the box below the message) which will then prevent it from needing to ask for USB permission in the future. Otherwise, permission is only granted for that boot of the device. 

There's a stack overflow discussion around the topic [here](https://stackoverflow.com/questions/40075128/android-usb-device-attached-persistent-permission). In short, we have to respond to the event of the device being plugged in instead of asking for permission when we want to connect to the device. 

Is the problem that you see Keppel open every time the device starts? We could look at smoothing out that flow if so (maybe just immediately closing or showing a message that the device is connected for instance).

**Comment by seadowg** [comment]
After discussing this with @tobiasmcnulty again, it seems like the ideal would be for nothing to be shown when a USB device is connected (and permission is granted). If this isn't possible, the backup solution would be to show a simple "OK" dialog with a message (like "Scanner connected").

**Comment by seadowg** [comment]
We've decided to leave this as-is for the moment.

**Comment by seadowg** [comment]
Reopening this as one of the devices we're playing with has an embedded scanner which gets "connected" on every unlock and pops up the Keppel settings. I'm wondering if we should make the following changes:

- Just show a toast with "Scanner connect" (or similar text) when a matched scanner is connected
- Add a "setup" button to settings that will connect/disconnect the scanner so that users can set up the default permissions (checking always allow) explicitly without needing to use a form.
